[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b469a646ffc0794e547525f6b5e9052fcce0178c"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "13f6e4596334ca1a8981d56fdf5401dff736c755818e22f966f9e501dccd8784"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbcbc313a48f6a04bb9824b05e2a6e25c72c261a"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "efbb492265ee083e68d201cd4f1bff15200e8d805d6ac524f021946b7a42fb7c"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d11ccec8426802572ef574ef74b5cf9ac5ffdae"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "a631120ed468397324e4b285c2f53732736c7bff7b457e58c3155e746868d8b4"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.aarch64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1a5e63d963c3451d9315c0d899e439aaa2ae749"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "38676e551e7714174ce5a0ad0da04414c78658c63973bb315b9d0112ebec5600"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.aarch64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b3e9e80638593995587c8e17aea66f957f9b873"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "a3a0553b6c545986dbcd1175df135a39f12444a13cf349e59389ee8c5f985c33"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "650d416feafe15ec07f76b5613bfe1b50d494052"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "cea2a9356b963325d24c36e451d5b8aaa594d6a11af78a1f2ba28467958ee8f6"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c56ff80635376dae600df59db93333a0b16dff9"
os = "macos"

    [[SEAL.download]]
    sha256 = "1a387327444ce0f20c749079add47a2253e6d48c672137f96653f02af1af9949"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6646ca657809cf607596b7e459bbb5c91bd02f96"
os = "macos"

    [[SEAL.download]]
    sha256 = "a194aa98b7045e47d604e32049bd7868cfbb09d248efe9db42ef43fee91499cb"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8e70942ee7579f0af3b9c2e303ebac612d8b2a6"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "9db7b11e5ad5105ee6ff7975cbfd0dc3ed677522e6411b16ca0f712dcf4d93cc"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d3954aae17835f5d878bf342f5f24f7e871e0db"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "ae8916f473a1a142b980067cd3ef883b61fdf970f67edeb8d77f8bcba2877568"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f143e5f5f1b84dd4eceda4074ec7a990b4055c53"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "069bf1776ca1ac8dcd990d4e0e72ac09e2a200a6955a958c03fc9399cf1b8d76"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d25a48ac2fa8809fac240942a201614141363711"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "548b71ec9ea460d507a62e857b88839822340b4aff29fb6b1ff5d77ecb542d4d"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2987c266d1dde4c1014d96b02f9cb580872d41ef"
os = "freebsd"

    [[SEAL.download]]
    sha256 = "09746cec827cbcc8559e997eca2a8192ab6499fe77071997dd92e976d1fc04be"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "301c873fb826dee4a5c01a86ca9856d254cbdb30"
os = "freebsd"

    [[SEAL.download]]
    sha256 = "97774798c9a902a59ccb2ec530162dd8617ec161c3bf3cded1bdf19eb05e3a2c"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+1/SEAL.v3.5.5.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
