[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55f8a149aa6a721a1b24b477fdee10353b079ef4"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "9fe46a72ffb6d211b61a840e771cd850d900ec9b014c8508919d759edce0bc87"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f16b11844e59391a32e2b5dceb5b6fcb0b3fb60"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "9a5d30e4ab6ed66be8904f669aaa5ce8446f6e3f098753813d9d045aef77f531"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26213d1038ab2c23823d379a62c76cdf2eb2e03d"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "d69fe70113bfb401b56ed6bc194da61dd048d4dfbf333e143420362e9d833dba"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.aarch64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "582dc5d47b2dd807b6fd1bc1f8e7cc6442291281"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "0d895acbcf9d5291325938354454d994e6881203239d8f59fe10dc370a676422"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.aarch64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e55b9c9825a0e1d8cc04e2c4dbc4caa6747ecec1"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "ab451a2aa5f5bb5a3b98f3518cd8cdfadb4c232371c062a79838ffde215055f6"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37c883070e95f85dafe0b7ebb4bf307918804db1"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "1b497336148b40050237a67a4e7ba098a8c0ac850350ab5bcab5d5bc49555fbd"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93e56fd101b76b8bf08cc9d9e5b735998d7e8a51"
os = "macos"

    [[SEAL.download]]
    sha256 = "1399f867afc2836710f85735be7aa75f3ee7127d327e737a2d5bc2d8c6d6a382"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fef4833ee09fc5ca30cf75725ebe8d22cea5bae5"
os = "macos"

    [[SEAL.download]]
    sha256 = "46ecd52c002513773f5f81245514a1fd74f5fb5d5a3b797a2fd02417e724040c"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b976225c857ca41e85dea12abc20bad6f30e736d"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "cad78eb218287df887e6b3d690c9bb4b53f67e4c0c89adaa7d14ea73e9114c2b"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f75bf4d56fe9001a59284c2c9bd4c45aeaf3b5e"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "600deb2f724a2120c2d983bfc19e3bec82165e04070c32cd3b1ba7c0d3efd2f7"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85bb5942aa1022f54344c3fde5f80ed996bfd2a4"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "b04a8a14d3798bde672af270bfc774dd58fb30f3b097afbdfaf1d6fa5915ba3e"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5867c5c81e86591f6ebad61e854e637683758d27"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "554634f5692b1860ee1721c97fcb73eed4af4b351c10a6478ccb99199d1c9816"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f5e6f3a13f78d295fe6502625007ea1812820ef"
os = "freebsd"

    [[SEAL.download]]
    sha256 = "3b1f351a37926ce05fc5aa7c49380bee38bf02aeb7b69cc3a1f727fb87e1e5c5"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "775decadd42c29e58276a61b661b42052c72a8e4"
os = "freebsd"

    [[SEAL.download]]
    sha256 = "0b865afcab5562b73318104892ad4cec5abe28aca8617c15282518e5a597b0f4"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.5.5+0/SEAL.v3.5.5.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
