[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7ba0765bc442d34e719f5b35a1a240e70ad022b"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "f22d6629fe4446e2e8a0a9b230589d5b06c6d735b07d01f62baa1e31bf91fb80"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.aarch64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebc6510e7f26e72dd00253f36b5bc7c847749a0f"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "8d043407a8586062acf6c09d2ec01a25eb2ba19d9c5bd01805189c5f8827a587"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f565c1bc09c604774e026e8853daffe2a8b281bb"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "7f92a2373225c80eee64d62e688d9a2621b21f8e0972b5f76f26640f3647f01f"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.aarch64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "383b2573ab7bc69ef9af6b06ebb89a509163fe1c"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "62df5556ea70b92cbb0d4bccb23509a3a51b35282cede7e04a45a2533010d4ed"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a285c07d7838939138e761093d1f31d424af065"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "07625edf48ff6c65cfc4dd3188be039eeac81ce6da8b9ba26995da79bcd3ab70"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dba35e2ddd2db6151c01ea2043944683a210903b"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "2eb6d2cf2a106d2b301ac75cf86e9d74d8c04505fe353fddb46c0155df0a20cd"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
git-tree-sha1 = "d728ea98665e2459e58e7043ce2698a4f7495e85"
os = "macos"

    [[SEAL.download]]
    sha256 = "753dd4088a6a9dbaac2791433594316408247f10ba4dea232a63ac6cac43efb2"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-apple-darwin.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b73b7be59acd9ad87560a7d3e5f98ccf7695dba2"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "80b36c8c18b1f35ee279b7a3bbfabb24fe4e90f0cf161caf585e7b73442ea7ac"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-linux-gnu-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "098fe6e2292cbf4947cdf5c2f169f0caf3f691d8"
libc = "glibc"
os = "linux"

    [[SEAL.download]]
    sha256 = "7e291527f738b429556fa0f60c3c961532d8bdd23e3040580059637aab669ea4"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d167bf7329be6a11232abb0b1aa47f0a9705cd7d"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "5307523f9be1d2cbc5812c110f240914ef9a56576c3e9cd9166e47c8c3a64365"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-linux-musl-cxx03.tar.gz"
[[SEAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cfcf978a6662bb91647e79a9e4444ea61031bc2"
libc = "musl"
os = "linux"

    [[SEAL.download]]
    sha256 = "1e8bb93b30aa635025ffbb8146605b4e1746e9f09c63a5e8f31a0a2dfe6bb6ca"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[SEAL]]
arch = "x86_64"
git-tree-sha1 = "4ecbbea0d65e4c63d61ee6d3351c5c713a0ce765"
os = "freebsd"

    [[SEAL.download]]
    sha256 = "617f8534d457cc0f87001d40bb44d7cc36b8fc00923ac8c7124b2003b4a17de3"
    url = "https://github.com/JuliaBinaryWrappers/SEAL_jll.jl/releases/download/SEAL-v3.6.2+0/SEAL.v3.6.2.x86_64-unknown-freebsd.tar.gz"
