# Autogenerated wrapper script for SEAL_jll for x86_64-apple-darwin
export libsealc

JLLWrappers.@generate_wrapper_header("SEAL")
JLLWrappers.@declare_library_product(libsealc, "@rpath/libsealc.3.6.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsealc,
        "lib/libsealc.3.6.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
